spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.50.119:3306/zscfyx?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  freemarker:
    cache: true
    settings:
      number_format: 0.######
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    port: 465
    host: smtp.ym.163.com
    username: xxxxx@xxxxx.com
    password: xxxxxxxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8087

mybatis:
  type-aliases-package: cn.fengyunxiao.nest.entity
  #mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    root: info
