package cn.edu.bjfu.igarden.entity;



/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newsmodules{
	private Integer Id;

	private String name;

	public Integer getId() {
		return Id;
	}

	public void setId(Integer id) {
		Id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
